# Fichier de configuration principal pour Netlify

[build]
  # Dossier contenant le site statique (HTML, CSS, JS client)
  publish = "public"
  # Dossier contenant nos fonctions serverless
  functions = "netlify/functions"

[functions]
  # Assure que nos fonctions utilisent bien Node.js
  node_bundler = "esbuild"

[[edge_functions]]
  # Chemin vers notre fonction "portier"
  function = "auth-gate"
  # URL sur laquelle cette fonction doit s'exécuter
  path = "/"

